version: '3.7'

# SWARM Configs
#================================================
configs:
  F-rexrayMysqlDb-mysql.cnf-v1:
    file: ./docker/rexray-mysql-db/mysql.cnf

  # HEALTHCHECKS
  F-healthcheck-mysql-v1:
    file: ./docker/_swarm/healthcheck/app_mysql_healthcheck.sh


# SWARM Secrets
#================================================
secrets:
  rexrayMysqlDb-MYSQL_DATABASE-v1:
    external: true
  rexrayMysqlDb-MYSQL_USER-v1:
    external: true
  rexrayMysqlDb-MYSQL_PASSWORD-v1:
    external: true
  rexrayMysqlDb-MYSQL_ROOT_PASSWORD-v1:
    external: true

# Volumes
#================================================

volumes:
  dobs:
    driver: rexray/dobs
    driver_opts:
      size: 1

services:

  rexray-mysql-db:
    image: mysql:5.7.24
    environment:
      - MYSQL_DATABASE_FILE=/run/secrets/rexrayMysqlDb-MYSQL_DATABASE
      - MYSQL_USER_FILE=/run/secrets/rexrayMysqlDb-MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/rexrayMysqlDb-MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/rexrayMysqlDb-MYSQL_ROOT_PASSWORD
    deploy:
      replicas: 1
    healthcheck:
      test: ["CMD", "app_mysql_healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - type: volume
        source: dobs
        target: /var/lib/mysql
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    configs:
      - source:  F-rexrayMysqlDb-mysql.cnf-v1
        target: /etc/mysql/conf.d/mysql.cnf
        mode: 0444
      - source:  F-healthcheck-mysql-v1
        target: /usr/local/bin/app_mysql_healthcheck
        mode: 0555
    secrets:
      - source: rexrayMysqlDb-MYSQL_DATABASE-v1
        target: rexrayMysqlDb-MYSQL_DATABASE
        mode: 0444
      - source: rexrayMysqlDb-MYSQL_USER-v1
        target: rexrayMysqlDb-MYSQL_USER
        mode: 0444
      - source: rexrayMysqlDb-MYSQL_PASSWORD-v1
        target: rexrayMysqlDb-MYSQL_PASSWORD
        mode: 0444
      - source: rexrayMysqlDb-MYSQL_ROOT_PASSWORD-v1
        target: rexrayMysqlDb-MYSQL_ROOT_PASSWORD
        mode: 0444

